title:            CodeInventory
description:      "Nerd's feeder!"
logo:             logo.png
disqus_shortname: codeinventorycom
share:            true
dropcap:	   true
# Change url to your domain. Leave localhost server or blank when working locally.
# or use the hint from http://jekyllrb.com/docs/github-pages/ to keep this the same 
# whether working locally or remotely. Start Jekyll with: jekyll serve --baseurl ''
url:        	 http://www.codeinventory.com

# Owner/author information
owner:
  name:           Amey Jadiye
  avatar:         ameyjadiye.jpg
  email:          ameyjadiye@gmail.com
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:    Programming is 1% knowledge, 2% ability and 97% getting the ability to work with the knowledge :)
  # Social networking links used in footer. Update and remove as you like.
  twitter:        ameyjadiye
  facebook:       ameyjadiye
  github:         ameyjadiye    
  instagram:      ameyjadiye
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    https://plus.google.com/u/0/+AmeyJadiye

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-46791108-1
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# Links to include in footer navigation
# For external links add external: true
links:
  - title: Home
    url: /
    external: false
    icon: home
  - title: Categories
    url: /categories
  - title: About
    url: /about

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Calcutta
future:      true
highlighter: pygments
markdown:    kramdown
paginate:    5
paginate_path: "page:num"

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   pretty

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

gems:
- jemoji

